# Generated by Django 3.2.9 on 2021-11-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='L3BTCUSDAsks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('px', models.FloatField()),
                ('qty', models.FloatField()),
                ('num', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='L3BTCUSDBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('px', models.FloatField()),
                ('qty', models.FloatField()),
                ('num', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
